apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "python-flask-proj1.fullname" . }}-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi