replicaCount: 2

image:
  repository: alon911/python-flask-proj1
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30007

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80